Repository antoine-mouchamps/pyfigure98, pull requests merged in 2023-10, with the labels that each got.

#11 Dev
  Examples/README_example.pdf
  Examples/example.pdf
  README.md
  example.py
  src/pyfigure98/Figure/_set_figure.py
Labels: documentation

#12 Added Badges
  .github/workflows/main.yml
  README.md
Labels: documentation

#13 close #4
  src/pyfigure98/Figure/Graph/__init__.py
Labels: fix

#15 closed #8
  src/pyfigure98/Figure/Graph/_axes_methods.py
Labels: fix

#14 #6: Fix a typo in addFigure()
  src/pyfigure98/Figure/_set_figure.py
Labels: documentation, fix

#16 Fixed some things in README
  .github/workflows/main.yml
  README.md
Labels: documentation

#22 Updated README for custom templates usage
  README.md
  test.json
Labels: documentation

#24 Fixed all typing errors
  .vscode/settings.json
  Examples/example.pdf
  src/pyfigure98/Figure/Graph/__init__.py
  src/pyfigure98/Figure/Graph/_axes_methods.py
  src/pyfigure98/Figure/Graph/_graph_methods.py
  src/pyfigure98/Figure/Graph/_place_holder.py
  src/pyfigure98/Figure/Graph/_plot_methods.py
  src/pyfigure98/Figure/__init__.py
  src/pyfigure98/Figure/_place_holder.py
  src/pyfigure98/Figure/_set_figure.py
  src/pyfigure98/Figure/_template_handling.py
Labels: fix

#25 Various small fixes
  example.py
  src/pyfigure98/Figure/Graph/_plot_methods.py
  src/pyfigure98/Figure/_set_figure.py
Labels: fix
